# Global Explosion Effect configuration. Applies to every gun that uses
# explosion, unless you add that gun to the 'Weapon_Blacklist'.
Explosion_Effects:
  Explosion_Particle_Density: 0.25
  Explosion_Particle_Spread: 1.0
  Smoke_Particle_Density: 0.5
  Weapon_Blacklist: []
    #- mygun

  Falling_Block_Break:
    Spread: 0.35
    Amount: 20
    Play_Break_Sound: true
  Falling_Block_Dust:
    Spread: 0.3
    Amount: 1

# Block sounds are played whenever a projectile hits a block.
# Note that water "splash" effects are handled by each gun in their own file.
Block_Sounds:
  Type: <BREAK, STEP, PLACE, HIT, FALL>
  Default_Randomness: 0.02
  Activate_Warden: true

  # In this section, you can override the sound a block makes when a projectile
  # hits it. For the most case, the default sound is good enough to give players
  # good sound queues, but sometimes you may want to add ricochet sounds or
  # more impactful sounds.
  #
  # The format is:
  # <block> <sound> <volume> <pitch> <randomness>
  Overrides:
    - "diamond_block custom:fx.ricochet 1 1 0.01"
    - "iron_block custom:fx.ricochet 1 1 0.01"
    - "$glass block_glass_break 1 1.3 0.01"

  # Material_Blacklist is used whenever you want a certain block to not make
  # any sound when hit.
  Material_Blacklist: []
    #- bedrock

  # Weapon_Blacklist is used whenever you want a specific gun to not make any
  # sound when it's projectile hits a block... Imagine a flamethrower for example.
  Weapon_Blacklist: []
    #- SquirtGun
    #- Flamethrower
