# Supported languages are "en-US", "fr-FR", "ru-RU", "us-UA"
# Added your language? Send it to me to have it added!
Language: "en-US"

# Controls what gets printed to console
# Valid levels are: OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL
# Generally, for testing, you might set Print_Level: FINEST to get more information
# A dev might ask you to set Stack_Traces_Level: WARNING to get information
# Alerts are used to warn admins in game when an error occurs... you can set that to OFF or SEVERE to limit alerts
Logger_Config:
  Print_Level: "CONFIG"
  Stack_Traces_Level: "OFF"
  Alert_Level: "WARNING"
  Max_Alerts_To_Show: 5
  Alert_Interval: 300  # 15 seconds * 20 ticks per second

# Global Explosion Effect configuration. Applies to every gun that uses
# explosion, unless you add that gun to the 'Weapon_Blacklist'.
Explosion_Effects:
  Explosion_Particle_Density: 0.25
  Explosion_Particle_Spread: 1.0
  Smoke_Particle_Density: 0.45
  Weapon_Blacklist: []
  #- mygun

  Falling_Block_Break:
    Spread: 0.35
    Amount: 20
    Play_Break_Sound: true
  Falling_Block_Dust:
    Spread: 0.3
    Amount: 1

# Block sounds are played whenever a projectile hits a block.
# Note that water "splash" effects are handled by each gun in their own file.
Block_Sounds:
  Enabled: true
  Type: BREAK    # <BREAK, STEP, PLACE, HIT, FALL>
  Default_Randomness: 0.02

  # In this section, you can override the sound a block makes when a projectile
  # hits it. For the most case, the default sound is good enough to give players
  # good sound queues, but sometimes you may want to add ricochet sounds or
  # more impactful sounds.
  #
  # The format is:
  # <block> <Sound/CustomSound>
  Overrides:
    - "diamond_block CustomSound{sound=fx.ricochet, noise=0.01}"
    - "iron_block CustomSound{sound=fx.ricochet, noise=0.01}"
    - "$glass Sound{sound=block.glass.break, pitch=1.3, noise=0.01}"

  # Material_Blacklist is used whenever you want a certain block to not make
  # any sound when hit.
  Material_Blacklist:
    - $wool

  # Weapon_Blacklist is used whenever you want a specific gun to not make any
  # sound when it's projectile hits a block... Imagine a flamethrower for example.
  Weapon_Blacklist:
    - Airstrike
    - Cluster_Grenade
    - Flashbang
    - Grenade
    - Semtex

# Block Particles are played when a projectile impacts with a block. Particles
# are "sprayed" out of the impact point.
Block_Particles:
  Enabled: true
  Amount: 4
  Spread: 0.5

  # The format is:
  # <block> <Particle>
  Overrides:
    - "$glass Particle{particle=BLOCK_CRACK, amount=8, noise=0.5 0.5 0.5, materialData=GLASS}"
  Material_Blacklist:
    - bedrock
  Weapon_Blacklist: []

# Break sounds are played when a projectile breaks a block using
# https://github.com/WeaponMechanics/WeaponMechanicsCosmeticsWiki/wiki/General#block_damage
#
# All the options are the same as the Block_Sounds options
Break_Sounds:
  Enabled: true
  Type: BREAK
  Default_Randomness: 0.02
  Overrides:
    - "$glass Sound{sound=block.glass.break, pitch=1.3, noise=0.01}"
  Material_Blacklist: []
  Weapon_Blacklist: []

# Break Particles are spawned when a projectile breaks a block using
# https://github.com/WeaponMechanics/WeaponMechanicsCosmeticsWiki/wiki/General#block_damage
Break_Particles:
  Enabled: true
  Amount: 8
  Spread: 0.5

  # The format is:
  # <block> <Particle>
  Overrides:
    - "$glass Particle{particle=BLOCK_CRACK, amount=12, noise=0.5 0.5 0.5, materialData=GLASS}"
  Material_Blacklist:
    - bedrock
  Weapon_Blacklist: []


# This is the "fake pumpkin" shown to players when they are in survival
# In older versions <1.12, use PUMPKIN instead of CARVED_PUMPKIN
Survival_Pumpkin:
  Type: CARVED_PUMPKIN
  Name: "<yellow>Scope Overlay"
  Lore:
    - "<gray>Clicking this will cause the scope to disappear"
    - "<gray>You can get it back by un-scoping then re-scoping"
  Custom_Model_Data: 1

# This is the "fake pumpkin" shown to players when they are in creative. Due
# to how creative players generate items, people in creative will always be
# able to duplicate this pumpkin.
# In older versions <1.12, use PUMPKIN instead of CARVED_PUMPKIN
Creative_Pumpkin:
  Type: CARVED_PUMPKIN
  Name: "&eScope Overlay"
  Lore:
    - "<gray>Clicking this will cause pumpkin duplication"
    - "<gray>This only happens in creative mode"
    - "<gray>Change this text in <i>WeaponMechanicsCosmetics</i> config.yml"
  Custom_Model_Data: 1
